### ISSUE TITLE
Checksum signature?

### ISSUE THREAD

**Issue by ress23** [LiskHQ/lisk-nano#1013]
What is the SHA-256 checksum of lisk-nano-win-1.2.1.exe?

Since the Bitcoin gold core hack I will not install any unverified wallets.

**Comment by slaweet** [comment]
There is [latest.yml](https://github.com/LiskHQ/lisk-nano/releases/download/v1.2.1/latest.yml) among the release downloads: https://github.com/LiskHQ/lisk-nano/releases/tag/v1.2.1 which contains sha512

**Comment by ress23** [comment]
Thank you!
