### ISSUE TITLE
Initialise account not showing

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#1022]
### Expected behaviour
From what blog post said, this https://cdn-images-1.medium.com/max/2000/1*DX7QuvnCxu77EETnjs-gqA.png should appear for new accounts.

### Actual behaviour
Well, it doesn't appear, even when other accounts with funds are saved.

### Steps to reproduce
generate new wallet

**Comment by slaweet** [comment]
Hi @karek314, that is expected behavior. The message is only shown once the account has some funds. Before that, there is 
1) no funds that need to be secured 
2) no funds to pay the fee for initialization transaction.
