### ISSUE TITLE
Getting error: cannot read property getPrimaryDisplay of null

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#1025]
### Expected behaviour
The error should not happen.
### Actual behaviour
Sometimes when launching Lisk Nano this error happens: `cannot read property getPrimaryDisplay of null`
![image](https://user-images.githubusercontent.com/1254342/34666043-c22d27d0-f462-11e7-913b-ee7ab94ea855.png)

### Steps to reproduce
Not sure

**Comment by joerodrig** [comment]
https://github.com/minbrowser/min/issues/170 looks like it's related and they were able to resolve it.

Quoting PalmerAL:
>It appears that OS X is triggering the activate event before the app is ready for some reason, which means that electron.screen hasn't loaded yet.
>According to the Electron docs, this event "usually happens when the user clicks on the application’s dock icon", but I guess it can happen at other times as well.

Their solution was to add an `appIsReady` flag at the `app.on("activate" => ...)` line [here](https://github.com/minbrowser/min/blob/267e90a113daf0a2accee0721c0659a6951df476/main/main.js#L188). You should be able to do something similar with Lisk [here](https://github.com/LiskHQ/lisk-nano/blob/a1a033b51920ffe710e9f49552f5b9c0b97a4eb3/app/src/main.js#L30)
