### ISSUE TITLE
Creating a new account on testnet, defaults back to mainnet

### ISSUE THREAD

**Issue by culshaw** [LiskHQ/lisk-nano#1031]
### Expected behaviour
I expected to create a new account on custom node/testnet, when the modal opens, it keeps the testnet or custom node selected

### Actual behaviour
The modal opens but the server dropdown reverts to mainnet

### Steps to reproduce
Open 1.3.2, select testnet, click new account.
Modal opens, and the dropdown reverts to mainnet.

**Comment by webmaster128** [comment]
Confirming. When using the source version on the development branch where Testnet is the default setting, the network always jumps back to Testnet. This means the network is always reset to the default.
