### ISSUE TITLE
Nothing in my Nano Wallet screen, after update (1.3.3)

### ISSUE THREAD

**Issue by katian** [LiskHQ/lisk-nano#1035]
### Expected behaviour
The Lisk Nano window display something

### Actual behaviour
The Lisk Nano window display nothing, only title bar...

### Steps to reproduce
on Ubuntu 17.10, after nano update from 1.3.2 to 1.3.3 from lisk-nano-linux-amd64-1.3.3.deb

**Comment by hirishh** [comment]
same issue with AppImage format on Ubuntu 16.04
Also Linux Mint is affected.

**Comment by simonmorgenthaler** [comment]
Same with Linux Mint

**Comment by slaweet** [comment]
There was an error in the build process. I did a new build from scratch and uploaded the new build of 1.3.3
