### ISSUE TITLE
Lisk disappeared from Nano Desktop

### ISSUE THREAD

**Issue by CryptoSender** [LiskHQ/lisk-nano#1054]
I still have the Lisk Nano 1.2.1 and last time I logged in I had voted for my Delegates. This time when I went to sign in all of my lisk has disappeared and does not show any transactions in my wallet? My main net number seems to be the same but a different address? Any idea as to where my list went?

Also wondering, I tried to download the 1.3.4 nano wallet but doesn't appear to have happened?

Any input would be great. Thanks!

**Comment by pcdinh** [comment]
Please ensure that your LISK Nano is connected to the mainnet, not testnet

**Comment by CryptoSender** [comment]
I am connected to the mainnet.. Why would my "address" have changed?

Who would I contact to see where my missing Lisk went? I have transaction
ID, however it appears that my "Address" changed on my Lisk Nano from when
I log in currently? My mainnet, number is the same, password got me in..
but the address is different and my lisk is no longer there?

2017/12/01 03:14:38 LSK 538.90000000 Completed

TxId14681011275057694330
Date2017/12/01 03:14:38
SymbolLSK
Address6284778596601540063L
Quantity538.90000000
StatusCompleted
AuthorizedYes
Confirmations0

**Comment by CryptoSender** [comment]
I did nothing different from the last time I logged into my Lisk and voted
for a delegate except for my address is different and Lisk is missing? Any
help would be appreciated on who I can contact to get these back.. Thanks.

**Comment by slaweet** [comment]
Hi @CryptoSender ,
please submit this to our help team at  https://help.lisk.io/ there is a circular button in the lower right corner to open the support form/chat.
