### ISSUE TITLE
Lisk Nano - Address Changed on Mainnet = lost LISK?

### ISSUE THREAD

**Issue by CryptoSender** [LiskHQ/lisk-nano#1057]
So I transferred my LISK to the Nano ledger desktop wallet back in December and recevied it on the address given below. I then went to stake my delegates about 3 weeks ago on the main net. I went to log back in roughly 8 days ago and all of my LISK were gone? There were no transactions and what I did notice is that my ADDRESS was different when I logged in than what I have written down and what appeared at the top left of my NANO desktop. 

2017/12/01 03:14:38 LSK 538.90000000 Completed

TxId14681011275057694330
Date2017/12/01 03:14:38
SymbolLSK
Address-6284778596601540063L
Quantity538.90000000
StatusCompleted
AuthorizedYes
Confirmations0

Has anyone ever had this happen to them? Any idea as to where my LISK may have gone or why my address is now different inside of my NANO DESKTOP WALLET?

What can/should I do?

Any help would be much appreciated. 

Thanks

**Comment by slaweet** [comment]
Hi @CryptoSender ,
please submit this to our help team at  https://help.lisk.io/ there is a circular button in the lower right corner to open the support form/chat.
