### ISSUE TITLE
Lisk Nano v2.0.0 rc1: Error-Message on startup (404 not found)

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-nano#1083]
Lisk Nano 2.0.0 rc1

By starting the app I get the following error. I already uninstalled and re-installed it but I still get it:

![grafik](https://user-images.githubusercontent.com/19614645/44300457-9f72ce80-a307-11e8-85e6-80a58c8dda07.png)

**Comment by slaweet** [comment]
@punkr0ck Thank you for the report. This is an error of auto-updater trying to get the release for the latest tag. I forgot that I cannot push a new git tag before doing the release on Nano. I just removed the `v2.0.0` tag and the error should be gone. 

We have a fix for this issue on Hub, but I think it's not worth porting to Nano as it's going to be discontinued. I'll just remember not to push tags before publishing a release.
