### ISSUE TITLE
Login problems with Lisk nano

### ISSUE THREAD

**Issue by hamid021** [LiskHQ/lisk-nano#1085]
Greetings to the members of Lisk,

I have problem with logging in Lisk nano after prolonged loading he indicates that
he has problems with the peer connection. The last time i Logged in was few months ago.
How can this issue be solved?

Kindest regards.

**Comment by slaweet** [comment]
Hello @hamid021 what version of Lisk Nano do you use? Only the latest 2.0.0, released last month, is compatible with the current Lisk protocol.

**Comment by hamid021** [comment]
I see my Nano version is outdated, 
I can not download it when I am at the nano 2.0.0. where is option that I can download it is very unclear?

**Comment by hamid021** [comment]
Thanks for your response I have successfully downloaded and logged in into my Lisk Nano account. 

Best regards!
