### ISSUE TITLE
Cannot login with updated Nano version

### ISSUE THREAD

**Issue by LISK17** [LiskHQ/lisk-nano#1089]
Hi Lisk Devs,

I've never attempted to sign into the Lisk Hub since it was introduced. Last time I've actually logged into my address was on Lisk Nano V 1.0.0 but haven't logged in since end of February. This version cannot connect to node when I went to update my votes today. I downloaded the Lisk Nano V2 and now it says " Passphrase contains unnecessary whitespace at the end". The 12 words I used to enter in original Nano had a space at the end of the last word and its not allowing me to enter my appropriate password because I cannot use a space at the end of the last word with the updated versions..  I tried with the mobile app and hub and same thing - if I put a space at the end of the 12th word it says "Passphrase contains 13 words instead of expected 12". I understand this update exists because a lot of people when copying their passphrases would carry extra space on the front or back by mistake and have the same problem the other way around but never had an issue with this on 1.0.0 . I can't be the only one who has done this. I need to be able to enter a space as the last character of my last word. I've logged into this address many, many, many, many times in the past as such, its where I keep and have been sending all my Lisk tokens. I have voted, created a second passphrase, and have continuously been sending my LSK to this address and using the hub to confirm the transactions since hub came out. Now I have no way of getting in. Although I spent 9 Lisk on 2nd passphrase and voting I will gladly send to a new wallet address but I will need access to a live version that allows the old log in style of entering and recognizing a space as a character. Please help! I have A LOT/ ALL of my beloved Lisk stored here in this address.

**Comment by webmaster128** [comment]
Hi @LISK17,

I can consult you privately to solve this issue. Please contact me as "prolina" on Lisk.chat or "webmaster128" on gitter.im

**Comment by webmaster128** [comment]
However, the easiest thing is to be able to skip the check of course. Looks like @slaweet is preparing something here: https://github.com/LiskHQ/lisk-nano/tree/disabled-passphrase-check

**Comment by slaweet** [comment]
Hi @LISK17 
I created a special build of Lisk Nano, that doesn't put any restriction on the passphrase
https://ci.lisk.io/test/lisk-nano/disabled-passphrase-check/#/

You can try that one to send your LSK to a new account.

**Comment by LISK17** [comment]
@slaweet THANK YOU SO MUCH! I was trying to figure this out in commander but this was easy I have recovered all my Lisk and sent to a new address. Many thanks for the prompt fix!
