### ISSUE TITLE
Error: No peer connection.

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk-nano#11]
I tried to login after generating a new passphrase.
And the following error occurred:

<img width="1237" alt="screen shot 2016-10-13 at 3 56 49 pm" src="https://cloud.githubusercontent.com/assets/937766/19363395/a2de5d38-9160-11e6-9110-8b368696946c.png">

**Comment by rferro** [comment]
@vrlc92 http://m.lisk.io is working normally now. Try again please. Ty!

**Comment by vrlc92** [comment]
Yes, http://m.lisk.io is working.
Thanks!
