### ISSUE TITLE
Remove Git Hooks from src/package.json

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-nano#111]
### Expected behaviour
The client should build without issue on node 6.10.1

### Actual behaviour
Building throws ELIFECYCLE errors under node 6.10.1

### Steps to reproduce
Build the source folder on windows and it will fail

**Comment by karmacoma** [comment]
Closed by a41fc90ac0c42cfb45c3a7cc9d6518f320e09ed5
