### ISSUE TITLE
NPM warns electron-prebuilt is depreciated and renamed to electron

### ISSUE THREAD

**Issue by Citizen-X** [LiskHQ/lisk-nano#12]
NPM states that **electron-prebuilt** will be depreciated by the end of 2016 and replaced with the name **electron**.

>  _As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016. https://www.npmjs.com/package/electron-prebuilt

#13

**Comment by rferro** [comment]
Closed by https://github.com/LiskHQ/lisk-nano/commit/27c631d405b113775df0d3028eef439160bc844d

**Comment by rferro** [comment]
Ty @Citizen-X
