### ISSUE TITLE
OSX Build is now --mac for electron builder

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-nano#120]
### Expected behaviour
When running the build for macos, the build should create .dmg

### Actual behaviour
The build fails saying unsupported flag

### Steps to reproduce
npm run dist:osx

**Comment by karmacoma** [comment]
Resolved by 5e2c31a1f9de77ef29b6f609921e67db39acc683 and 761df6c0dd4e358d5a925dd8a52207856093ce53
