### ISSUE TITLE
Scientific annotation displayed on transaction history

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-nano#128]
### Expected behaviour
Show the actual number, not the scientific annotation.

### Actual behaviour
Show the scientific annotation, not the actual number.

### Steps to reproduce
Send a transaction of 0.00000001 and on the transaction history it will appear as 1E-8

<img width="2372" alt="screen shot 2017-04-19 at 1 59 23 pm" src="https://cloud.githubusercontent.com/assets/17442402/25223798/be10ab24-25bc-11e7-96ad-98396fa41811.png">

**Comment by slaweet** [comment]
Will be fixed once this PR is merged https://github.com/LiskHQ/lisk-nano/pull/130

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk-nano/pull/130
