### ISSUE TITLE
Peer selection highlighted as errorneous when passphrase invalid

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#136]
### Expected behaviour

Passphrase field is highlighted when input is invalid.

### Actual behaviour

All input fields are highlighted as having an error i.e. "Choose a peer".

<img width="802" alt="lisk nano firefox wednesday 19 april 2017 at 12 44 09" src="https://cloud.githubusercontent.com/assets/8068/25378160/d1d13e30-29a9-11e7-911f-9d79f89e494b.png">

### Steps to reproduce

Enter an invalid passphrase upon login, e.g. "x".

**Comment by slaweet** [comment]
This gets solved in another PR:
https://github.com/LiskHQ/lisk-nano/pull/164/commits/d5e59a8cd20e0758b326a8ca1d9d6f4b0f8ef36c#diff-dd66c391e21ab333fa26dc51580014d9L7
