### ISSUE TITLE
Delegate account is not clearly indicated

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#141]
The following might be already resolved by work going into: https://github.com/LiskHQ/lisk-nano/issues/22. Opening issue anyway in order to bring attention to it.

### Expected appearance

Some indication that the account is a delegate. Possibly displaying username alongside or instead of address.

### Actual appearance

Address is shown but with no indication account is a delegaate:

<img width="390" alt="lisk nano firefox wednesday 19 april 2017 at 13 01 05" src="https://cloud.githubusercontent.com/assets/8068/25383063/9c735474-29ba-11e7-9069-c3e133fe6c64.png">

Forging tab is made visible. Username shown to left of "LSK Earned" (this could be made bolder):

<img width="957" alt="image" src="https://cloud.githubusercontent.com/assets/8068/25383083/bc103dce-29ba-11e7-8490-806af470a309.png">

### Steps to reproduce

Login as a delegate.

**Comment by alihaghighatkhah** [comment]
@karmacoma This is solved in #168

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk-nano/pull/168
