### ISSUE TITLE
New passphrase window sometimes pops-up more than once

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#16]
<img width="812" alt="screen shot 2016-10-27 at 12 00 39" src="https://cloud.githubusercontent.com/assets/9548618/19763134/0cf7407c-9c3d-11e6-9926-422dc0c28643.png">

Hard to reproduce, just sometimes pop up twice, sometimes it removes previous one, sometimes there are 2 windows stacked.

**Comment by karek314** [comment]
Actually it's easy to reproduce, just keep moving mouse around few moments after it appear to finish generation.

**Comment by rferro** [comment]
@karek314 I could not reproduce this bug. which browser you are using?

**Comment by karek314** [comment]
Safari Version 10.0.1 (11602.2.14.0.7)

**Comment by Tosch110** [comment]
Is this already fixed? I was trying to reproduce the bug on Safari 10.0.3 and after I kept the mouse moving a few moments nothing changes.

**Comment by karek314** [comment]
**Safari Version 10.0.3 (12602.4.8)**
Bug still exists, however it's sometimes hard to reproduce. I would consider this as minor ux/ui bug.

- As soon passphrase is being generated, view should be forced to unselect, because animation acts weird

- Fix double appearing

Video below, let me know as soon you check so i can remove vid.

https://www.youtube.com/watch?v=0OgaTjbECQg

**Comment by Tosch110** [comment]
Thank you @karek314 
We are investigating this issue!
