### ISSUE TITLE
Create a modal that can compile any child component

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-nano#163]
### Expected behaviour
We want to have a modal component of any type, which uses `mdDialog` to show/hide a child component. the child component can be any component provided using the constructor.

### Actual behaviour
We are using modals along with the modal content in a single component which is not DRY.

### Steps to reproduce
These compound components are some examples of non-DRY implementation:

 - `/components/login`  
   - `save`  
   -  `passphrase`  
 - `/components/main`  
   - `setSecondPass` 
 - `/components/send`  
   - `sendModal`

**Comment by slaweet** [comment]
There was an attempt to do this here: https://github.com/LiskHQ/lisk-nano/blob/development/src/services/dialog.js#L95-L111
But it's not finalised and not used anywhere.

**Comment by slaweet** [comment]
Done looong time ago in https://github.com/LiskHQ/lisk-nano/pull/308
