### ISSUE TITLE
Received "Error - An error occurred while sending the transaction." message, but Transaction still went through

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-nano#19]
I was using peer node02.lisk.io and after clicking "Send", the transaction stalled for a bit, and ended up giving an error message. After some minutes, the transaction was successfully transmitted to the blockchain.

https://explorer.lisknode.io/tx/2410196519953974551

**Comment by rferro** [comment]
Hi @jfernanz! I released version 0.1.2 and I think this issue was fixed. Try again please. Ty

**Comment by karmacoma** [comment]
@jfernanz @rferro This issue is resolved?

**Comment by slaweet** [comment]
I couldn't reproduce this error. It's most likely have been fixed.
