### ISSUE TITLE
Upon starting the application, caps lock symbol pops up without caps lock being on

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-nano#211]
### Expected behaviour
If caps lock is off, no symbol should appear

### Actual behaviour
Caps lock is off but the symbol pops up upon startup and is unresponsive for a few seconds

### Steps to reproduce
- Start the application
- Look at screen
- See the caps lock symbol
- Check your caps lock (make sure it's off)
- Quit application
- Start it again
- See the caps lock symbol
- 100% sure your caps lock is off, but still see the symbol
- Log an issue

<img width="1149" alt="screen shot 2017-05-12 at 3 27 56 pm" src="https://cloud.githubusercontent.com/assets/17442402/26000036/a1100ae8-3727-11e7-98a6-b778ab2e4d7a.png">

**Comment by karmacoma** [comment]
@jfernanz I can only reproduce if caps lock lock is **on** before starting application. Which is normal behavior in order to warn user the lock is on. Otherwise it is not showing.

**Comment by jfernanz** [comment]
@karmacoma Yeah, I could only reproduce it during the first time I booted it. After a restart it was fixed and I'm no longer receiving the problem. The process I used for upgrading from old version to the new version was to `replace` the old application.

**Comment by slaweet** [comment]
Closing the issue as it cannot be reproduced. If it happens again please reopen.
