### ISSUE TITLE
Revert "Transfer" back to "Send"

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#215]
### Expected appearance

Button and window title originally used the verb "Send".

### Actual appearance

Button and window title now uses the verb "Transfer".

![image](https://cloud.githubusercontent.com/assets/8068/26054045/8a2baf6c-396b-11e7-88a2-f4ff9336e589.png)

![image](https://cloud.githubusercontent.com/assets/8068/26054026/79fd93a8-396b-11e7-8842-72fb0cbe74e5.png)

### Steps to reproduce

Launch the development version of `1.0.0`.

**Comment by karmacoma** [comment]
Should be changed here also imo:

![image](https://cloud.githubusercontent.com/assets/8068/26055912/35b46cb4-3973-11e7-8328-b744741d9a76.png)

**Comment by MaxKK** [comment]
I agree to this, Lisk is mainly a utility token and not a cryptocurrency. Therefore, send makes more sense. A quick market research approves it. Multiple wallets use "send".

https://www.exodus.io/img/exodus-wallet-btc@2x.jpg
https://support.coinbase.com/customer/portal/attachments/712389
https://jaxx.io/images/firefox.jpg

**Comment by slaweet** [comment]
I would like to keep the file names in sync, so if we are renaming Transfer to Send, we should also rename `transfer.js` to `send.js` and the same for `*.pug`, `*.spec.js` and `*.less`. I would suggest to do this issue only after https://github.com/LiskHQ/lisk-nano/pull/212 is merged, because it moves all the files to a new location.

**Comment by MaxKK** [comment]
Yes, let's do it!

**Comment by alepop** [comment]
@MaxKK which options in the end `Transfer` or `Send`? I'm asking because my PR with the fix was closed.

**Comment by MaxKK** [comment]
I was talking about the change in the UI. I ping Oliver so he can give input on the file name changes. @karmacoma




Best regards, 
MK
