### ISSUE TITLE
Delegate name shown is too timid

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#219]
### Expected behaviour

As a user I expect the delegate name to be **bolder** and therefore more prominent. It's my identity after all.

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/8068/26055983/983fe67e-3973-11e7-90b0-d83bc22c0a77.png)

In both cases where the name is shown they both look rather timid, and additionally not clear that they represent my delegate's identity.

### Steps to reproduce

Log in as a registered delegate.

**Comment by MaxKK** [comment]
What do you think about replacing the address with the delegate name (title needs to be changed to "Delegate") and where currently the name is visible in small, we could put the address in small.
