### ISSUE TITLE
Tabs styling is not very distinctive

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#220]
### Expected appearance

The tabs should be more visually distinctive. Some background color for active, inactive tabs would help imo.

### Actual appearance

![image](https://cloud.githubusercontent.com/assets/8068/26056217/abb7fc7c-3974-11e7-93ed-cc29187c1b30.png)

### Steps to reproduce

Launch the development version of `1.0.0`.

**Comment by MaxKK** [comment]
What do you think about something like that?

![abb7fc7c-3974-11e7-93ed-cc29187c1b30](https://cloud.githubusercontent.com/assets/9763350/26117536/2f0e982c-3a67-11e7-9652-badbaf07fffe.png)
