### ISSUE TITLE
Add forging center

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#23]
Add forging center for registered delegates to view:

- Forging rank, productivity, approval graphs
- LSK earned / forged
- Forged blocks

**Comment by slaweet** [comment]
To start the discussion on what should the forging center look like I created a branch with some html mockups: https://github.com/slaweet/lisk-nano/tree/23_forging-center

I covered three states, that can be trigered by url parameters when running it on localhost:

- Not a delegate
http://localhost:8080/#?noforging=true
![forging-no-forging](https://cloud.githubusercontent.com/assets/1254342/24547638/23b72cfc-1611-11e7-8d6b-78ff9a2d6390.png)

- No blocks forged
http://localhost:8080/#?noblocks=true
![forging-no-blocks](https://cloud.githubusercontent.com/assets/1254342/24547657/3c86ce40-1611-11e7-84d1-cd42c21f8e2e.png)

- Active delegate
http://localhost:8080/
![forging](https://cloud.githubusercontent.com/assets/1254342/24547663/43986ee6-1611-11e7-95df-10651d379467.png)

**Comment by 4miners** [comment]
Looks good, but can we move that to separate page?

**Comment by slaweet** [comment]
@4miners I agree that there's too much stuff on the page, though I'm not sure how exactly to do switching to a separate page.
Maybe we don't need the "send" form displayed all the time and can move it to a popup dialog opened by a new button like this:
![remove-send-block](https://cloud.githubusercontent.com/assets/1254342/24551547/23f17288-1623-11e7-99cd-f6d9f87b0ee1.png)
