### ISSUE TITLE
Wallet address overflow their block

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisk-nano#235]
### Expected behaviour
Maybe need to truncate wallet address but then need to implement functional `click to copy`. Or reduce font-size?
<img width="681" alt="screen shot 2017-05-16 at 14 53 24" src="https://cloud.githubusercontent.com/assets/922338/26104807/21930904-3a48-11e7-8b55-a74e9cb34b1b.png">

### Actual behaviour
<img width="676" alt="screen shot 2017-05-16 at 14 52 58" src="https://cloud.githubusercontent.com/assets/922338/26104773/00466ea8-3a48-11e7-9517-9d028efe335c.png">

### Steps to reproduce
Open Lisk Nano, log in and resize window

**Comment by slaweet** [comment]
An easy fix would be to make the overflow scroll vertically - still can select the whole text.
```
.address {
   overflow-x: auto;
}
```
Though It probably won't look good with the scrollbar that is used in Windows

**Comment by slaweet** [comment]
Closing as duplicate to #389
