### ISSUE TITLE
Sending a transaction to own address displays the sent transaction but not the received

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-nano#236]
### Expected behaviour
Sent and received transaction should both be present on history

### Actual behaviour
Only sent transaction is displayed

### Steps to reproduce
Send a transaction to your account (the one you're logged into)
Transaction sent will be displayed; transaction received will not
![screen shot 2017-05-16 at 2 11 05 pm](https://cloud.githubusercontent.com/assets/17442402/26105248/8832e3f2-3a41-11e7-944c-b40b10236ccb.png)

**Comment by slaweet** [comment]
Why do you need to send to your account? Should that be allowed at all?

**Comment by karmacoma** [comment]
@slaweet Registrations and votes are self-referential.
