### ISSUE TITLE
Show desktop notifications for changes

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-nano#253]
### Expected behaviour
Would be cool if we can show notifications when the account's balance has been changed. I mean when a deposit happens

### Actual behaviour
Presently we don't have any notification for this kind of changes.

### Steps to reproduce
- Send some funds to your account.
- You won't get any updates unless with opening the application and reading the balance.

**Comment by alepop** [comment]
@alihaghighatkhah I made this feature. but still, need to write some tests. And what kind of text need to display on notification?

**Comment by alihaghighatkhah** [comment]
@alepop Good job! I was thinking about showing the value of the change, e.g. _You've received xx.xx LSK_.
