### ISSUE TITLE
Add a receive button

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-nano#254]
### Expected behaviour
I would suggest adding a button that generates more focus and description on address. may be showing a simple modal that emphasises the Address for receiving funds. I know our address is obvious up there, but it may worth showing in bigger font size or Qr code

### Actual behaviour
It might not be clear for some users that they should use the value under the title Address for receiving funds.

**Comment by tao** [comment]
I spent like 20 mins searching the internet trying to figure this out, I really thought the address for receiving funds was missing... I think I was looking for something more like single use 0x addresses and didn't even notice the lisk one in the grey box.

**Comment by alihaghighatkhah** [comment]
@tao Yes, You're right. specially because the structure of the string is different for each . blockchain, it's worth having a receive button to make it easier to recognize.

**Comment by slaweet** [comment]
The receive button could be also in transaction list when the list is empty. Something like: "You have no transactions yet, [Receive LSK]"
