### ISSUE TITLE
Send all funds message

### ISSUE THREAD

**Issue by stenea** [LiskHQ/lisk-nano#286]
On mouse over on "Balance" I have a floating message saying " Send all funds". Do we really need that text?If yes, maybe should be refined.
![send all funds](https://cloud.githubusercontent.com/assets/4835177/26631343/3729f0b2-4613-11e7-9f9f-25e495760979.png)

**Comment by slaweet** [comment]
Maybe it could say "Click to send all funds" instead...

**Comment by stenea** [comment]
Yes, I think it would be a more clear message. I didn't even know that was a button :D

**Comment by Jaxkr** [comment]
In the release candidate I get this message on hovering address, node, and balance.
