### ISSUE TITLE
Draw the thin gray line through the end at the 3-dot menu

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#297]
FIX #296 FIRST!!

### Expected behaviour
A continous line

### Actual behaviour
It stops before the 3dot menu.

### Steps to reproduce
Open up modals with this extra menu. E.g. send modal.

![3dots-line](https://cloud.githubusercontent.com/assets/9763350/26650756/c3efc22e-464a-11e7-8efe-199b665595c5.jpg)

**Comment by slaweet** [comment]
FIxed in https://github.com/LiskHQ/lisk-nano/pull/306
