### ISSUE TITLE
Add a border-radius to the main menu

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#298]
### Expected behaviour
Every box is slightly rounded, but the main menu isn't. It should be as well.

### Actual behaviour
It's a sharp square.

### Steps to reproduce
Login. -> Click on the 3-dots at the top right corner.
![main-menu-square](https://cloud.githubusercontent.com/assets/9763350/26650887/30c2dd0a-464b-11e7-90f9-ae6c4ee389d1.jpg)

**Comment by slaweet** [comment]
FIxed in https://github.com/LiskHQ/lisk-nano/pull/306
