### ISSUE TITLE
Add shadow to the TRANSACTIONS menu entry

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#299]
### Expected behaviour
The material design shadow of the boxes should be continued in the navigation.

### Actual behaviour
There is no shadow.

### Steps to reproduce
Login.

![navigation-shadow](https://cloud.githubusercontent.com/assets/9763350/26650956/73111d02-464b-11e7-9afc-354b2d05fb9f.jpg)

**Comment by alihaghighatkhah** [comment]
I suppose there is no shadow to imply the feeling that the transaction tab header is joined to body of the active tab. unlike the other tab heading which is separated by shadow.
