### ISSUE TITLE
Document source code using YUIDoc

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#30]
We should document the `lisk-nano` source code using: http://yui.github.io/yuidoc/

New code can be documented immediately: http://yui.github.io/yuidoc/syntax/index.html

Existing code we cover here, module by module.

**Comment by alihaghighatkhah** [comment]
Please clarify:
 - Should all the public method of the services get documented?
 - Should we define types for parameters?
   - If yes, Should we check for parameter types in logic?
 - Should we add parameter description
 - Should we define return types?
   - If yes, Should we restrict functions to a single return type? 
 - Should we use descriptions?

**Comment by alihaghighatkhah** [comment]
As @karmacoma suggested we're going to start with:
 - Only for public methods.
 - Define types for parameters.
 - No descriptions yet.
