### ISSUE TITLE
VOTING page is not loading on a new account

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#300]
### Expected behaviour
I should see all delegates when I switch to the VOTING page.

### Actual behaviour
It's never loading.

### Steps to reproduce
Make a new account (non delegate), login and switch to the voting tab. I think it has something to do with my account not being a delegate or have no transactions.

**Comment by slaweet** [comment]
Duplicate to https://github.com/LiskHQ/lisk-nano/issues/288
