### ISSUE TITLE
All forms should look and feel the same

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#301]
### Expected behaviour
All forms should look and feel the same, follow the same rules and design guidelines.

### Actual behaviour
Sometimes they are very different.

### Steps to reproduce
The vote for delegates and search for delegate forms are wrong. E.g. the send form is correct.

![form-conformity](https://cloud.githubusercontent.com/assets/9763350/26651197/30cf0cbe-464c-11e7-8e16-91243361b228.jpg)

**Comment by alihaghighatkhah** [comment]
I changed the search form to look similar to send form. but the vote form is technically different from the others and to make it behave the same we need to monkey patch Angular material, but I'm not sure this worth doing it. what do you think?

**Comment by MaxKK** [comment]
Best regards, 
MK

**Comment by MaxKK** [comment]
Why is it technically different? Is that necessary?

Best regards, 
MK
