### ISSUE TITLE
Align modal headers with the forms and buttons

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#302]
### Expected behaviour
The headline of the modal should be aligned with everything else.

### Actual behaviour
It's a bit too far to the left. This goes for all modals!

### Steps to reproduce
Open any modal. This goes for all modals!

![align-modal-header](https://cloud.githubusercontent.com/assets/9763350/26651391/d0b153f4-464c-11e7-9e92-a4f695473bbe.jpg)

**Comment by slaweet** [comment]
Fixed in https://github.com/LiskHQ/lisk-nano/pull/306
