### ISSUE TITLE
Rank is not displayed while searching

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#303]
### Expected behaviour
Rank should remain displayed while searching for delegate to vote

### Actual behaviour
Rank disappears right away when searching ends.

### Steps to reproduce
Search for delegate by name

**Comment by slaweet** [comment]
This gets fixed when server nodes are updated to Lisk core 0.9.0, which is planned prior to Lisk Nano 1.0.0 final release.

**Comment by slaweet** [comment]
Lisk core 0.9.0 released some time ago. Closing this issue.
