### ISSUE TITLE
Voting transaction does not appear right away after voting

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#304]
### Expected behaviour
Voting transaction should appear instantly with pending status.(as any other)

### Actual behaviour
Voting transaction does not appear right away after voting

### Steps to reproduce
Vote

**Comment by slaweet** [comment]
I can reproduce this on latest final release `1.0.2`. But the latest release candidate of `1.1.0` no longer has this issue, since the code has been rewritten.
