### ISSUE TITLE
FPS rate drops while loading more than 200-400 items (delegates/votes/transactions)

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#305]
### Expected behaviour
Should not flash while scrolling fast.
Should work smoothly even when user scrolls down and load more than 10k items, it seems that items which are not currently displayed are not dynamically deallocated from view.

### Actual behaviour
FPS rate drops while loading more than 200-400 items (delegates/votes/transactions) and becomes lagging, moreover interface is "flashing" while scrolling down fast.

### Steps to reproduce
Scroll down

**Comment by slaweet** [comment]
This is actually duplicate to https://github.com/LiskHQ/lisk-nano/issues/260 , which also contains some info on how we plan to handle the issue.
