### ISSUE TITLE
Official nodes distribution

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#318]
To decrease possibility of downtime and incapability to use Lisk Nano for regular end user who may not be capable to define custom node - by diversifying all official Lisk nodes to various locations and various independent datacenters.

**Comment by Isabello** [comment]
This is not an issue that belongs on github.

**Comment by MaxKK** [comment]
Thank you Karek, Oliver already has some plans pretty much aligned to yours and we will discuss it in a special meeting here at the HQ soon. Like Isabella pointed out GitHub is the wrong place to discuss this. It's an infrastructure discussion/problem, we use GitHub only for development related things - i.e. things with code. 

Thanks.
