### ISSUE TITLE
A blue border around "Show all columns" menu

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#323]
### Expected behaviour
No blue border.

### Actual behaviour
It shows a blue, pixelated border.

### Steps to reproduce
Login.
Switch to forging tab of an active delegate.
Click on the 3-dots next to "Forged blocks".

I can't take a screenshot of it. It has something to do with the text or so being "marked" or "active".

**Comment by slaweet** [comment]
I could make a screenshot:
![screen shot 2017-06-06 at 17 04 42](https://user-images.githubusercontent.com/1254342/26836121-4f100556-4ada-11e7-9e57-756e6afefcfb.png)
Though I don't know how to control the thing. Looks like something Mac-related.

**Comment by MaxKK** [comment]
Looks super strange. Maybe @reyraa has an idea?

**Comment by reyraa** [comment]
@slaweet this would work:
`outline: none;`

**Comment by alepop** [comment]
@MaxKK @reyraa @slaweet `outline: none;` of course, will fix the issue. But what about accessibility?

**Comment by MaxKK** [comment]
What do you mean with accessibility, @alepop ?

**Comment by alepop** [comment]
I mean people who can not use a mouse and use the only keyboard for navigation. Then they cannot understand what element is in focus now. Maybe I'm exaggerating the problem.
