### ISSUE TITLE
Add infinity scroll to "Forged blocks"

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#327]
### Expected behaviour
That you can just scroll down and new forged blocks appear.

### Actual behaviour
There is a "LOAD MORE" button, even though "Transactions" and "Voting" have infinity scroll.

### Steps to reproduce
Login. Open Forging tab with an active delegate.

**Comment by reyraa** [comment]
The reason you see "Load more" button in the page is that your screen is too big to be filled with 10 transactions. Most of the times you don't care about the old transactions and you just want to know about the recent ones. so it's wasteful to call say 5 times and load 50 transactions to fill a 27 inch iMac! TBMK, this a common UX approach. but  If fixed an issue caused a glance in load more button.

**Comment by MaxKK** [comment]
Ok!
