### ISSUE TITLE
After the confirmation of a 1st/2nd passphrase, add another step

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#331]
### Expected behaviour
We should definitely add an explanation text as a third modal which educates the user that if he loses the passphrase he loses access to his account forever and that once he closes the modal, the password is nowhere saved, unless he took care of it. Maybe add an option to download it locally to the computer.

### Actual behaviour
It just closes and that's it.

### Steps to reproduce
Create a new account or add a second passphrase.

**Comment by MaxKK** [comment]
For the second passphrase the final confirmation screen should just be a final warning. Which explains exactly what the user is doing and if he loses the passphrase he will lose access.

For the first passphrase however it should be a disclaimer warning of the risks. 


Please prepare the code, I will send you the text tomorrow or so.

**Comment by reyraa** [comment]
Since after registration completes, there's no way to revert, I think the better approach is to include the introduction step to the beginning of the procedure. An implementation of this approach is ready in #359

**Comment by MaxKK** [comment]
Ok.
