### ISSUE TITLE
Remove "input names" feature from Voting tab

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#343]
### Expected behaviour
Voting tab does not contain button "input names"
Long term, we want the feature, but currently, there are too many ways to vote so we'll just simplify it and think about how to reintroduce the feature in a better way in the future.
### Actual behaviour
Voting tab contains button "input names"

**Comment by Isabello** [comment]
im not sure if i agree with removing it. this is a huge time saving feature
for end users. could it be implemented instead like lisk-ui
