### ISSUE TITLE
Window jumps to top when loading more transactions.

### ISSUE THREAD

**Issue by mrv777** [LiskHQ/lisk-nano#361]
### Expected behaviour
When you scroll down and it loads more tx's and the window stays there

### Actual behaviour
When you scroll down and it loads more tx's, the window jumps back up to the top and I have to scroll back down.  It seems to redraw the entire display instead of just apending on the additional transactions at the bottom.

### Steps to reproduce
Just scroll down on the transactions page.

**Comment by simonmorgenthaler** [comment]
I can confirm that issue. Other auto extending lists like on the voting and forging tab work fast, smooth and as expected.
