### ISSUE TITLE
"Invalid transaction timestamp"

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#365]
Sometimes i get "Invalid transaction timestamp" while sending transaction. After retrying few times it works fine.

**Comment by Isabello** [comment]
You need to fix your local clock.

**Comment by karek314** [comment]
My local clock is just fine. I'm not the only one with this issue.

**Comment by slaweet** [comment]
In addition to mitigating this in lisk-js https://github.com/LiskHQ/lisk-js/issues/191 we could also provide a more user-friendly error message when this happens.

**Comment by Xue217** [comment]
It happens to me too, so I  just change my local clock backward and then it worked.

**Comment by slaweet** [comment]
Fixed in `1.0.2` patch release.
