### ISSUE TITLE
rc2 scrolling down cause reload

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#366]
### Expected behaviour
scrolling down transaction list should allow to do so

### Actual behaviour
scrolling down transaction list at some point causes entire view to reload, view is being reset to top, loading bar appears and transaction view is reloaded

### Steps to reproduce
scroll down transaction list on account with lots transactions

**Comment by Isabello** [comment]
This is a duplicate of this issue:
https://github.com/LiskHQ/lisk-nano/issues/361
