### ISSUE TITLE
Address and balance overflows on smaller screen

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#389]
### Expected behaviour
Address and balance should work also on smaller screen
### Actual behaviour
Address and balance overflows on smaller screen
![narrow-top](https://user-images.githubusercontent.com/1254342/27034771-410a6380-4f7f-11e7-8e9f-deff65ec9dd5.png)

### Steps to reproduce
Log in, adjust window width to ~720px

**Comment by alepop** [comment]
#235
