### ISSUE TITLE
Remove the "Load More" link at the bottom of the first few transactions

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-nano#402]
I think it would be more convenient if the additional transactions are loaded automatically when scrolled down, as on the Votings and Forging pages. Everything should work the same way

**Comment by Isabello** [comment]
@alepop has requested to take this issue.

**Comment by alepop** [comment]
Currently behavior on Transaction tab a same as on Voting and Delegate tabs. What version of `lisk-nano` do you use?

**Comment by slaweet** [comment]
The difference is if you have bigger screen height then the initial 10 transactions:
![load-more](https://user-images.githubusercontent.com/1254342/27119681-0f03cd46-50e1-11e7-8588-c5d865c5dd64.png)
In voting, we start with displaying 20 delegates (fetch 100), so this is less likely. In forging there is more stuff at the top, so again less likely to happen.

**Comment by alepop** [comment]
@slaweet thanks

**Comment by simonmorgenthaler** [comment]
I tested with 1.0.0.rc3. I have the same image as @slaweet (with the Load more link)
