### ISSUE TITLE
Clicking anywhere after generating passphrase break "ctrl+a" selection scope

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#403]
### Expected behaviour
CTRL+A selection should always focus on passphrase only

### Actual behaviour
CTRL+A works correctly if user do not click before using ctrl+a shortcut

### Steps to reproduce
Correct - generate passphrase, ctrl+a = works fine
Broken - generate passphrase, click anywhere, ctrl+a = selects everything

**Comment by alepop** [comment]
I don't think that is a bug because it is a standard behavior. I think it is an enhancement.
