### ISSUE TITLE
Delegate search output always has duplicate entries

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-nano#415]
### Expected behaviour
You search for a delegate and it finds it.

### Actual behaviour
You search for a delegate and it finds it, but it shows it 2 times.

### Steps to reproduce
Search for a delegate.

![double-entry](https://user-images.githubusercontent.com/9763350/27174028-ea976956-51ba-11e7-87fd-539f55dcb054.png)

**Comment by Isabello** [comment]
This is a bug on testnet, Not Nano.
