### ISSUE TITLE
Not able to use my public node anymore without added port 8000 

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-nano#424]
### Expected behaviour
Nano should accept `https://liskwallet.punkrock.me` as custom node. 

### Actual behaviour
It doesn't allow: `https://liskwallet.punkrock.me`
Only allowed: `https://liskwallet.punkrock.me:8000`
Didn't not allow `https://liskwallet.punkrock.me:2443`, even if my stuff is routed to it.

### Steps to reproduce
Put in `https://liskwallet.punkrock.me` as custom node.

**Comment by slaweet** [comment]
Fixed by  13c0719 which is now in master branch, so closing this issue.
It didn't close automatically because it was not merged to development branch because that one is in the middle of React migration and doesn't contain the changed code anymore.
