### ISSUE TITLE
Lisk Nano Vote Button : "Invalid transaction timestamp. TimeStamp is in the Future"

### ISSUE THREAD

**Issue by hen42** [LiskHQ/lisk-nano#458]
Hi there,
Clicking the Voting Button in Lisk Nano version 1.0.0  doesn't work correctly
I get some error saying "TimeStamp is in the future".

However, After clicking about 7 times the vote finally went trough.

Seems related to #365

**Comment by Isabello** [comment]
Known issue with end user clocks.

Please correct your clock.

**Comment by hen42** [comment]
I think my Clock is Ok, It is set automatically by Windows 10. It is the same as on my smartphone minus 7 seconds.

**Comment by slaweet** [comment]
Closing as duplicate to #365
Note that the wording of the error message was changed in Lisk core to be more descriptive after #365 was reported.

**Comment by icyourclam** [comment]
Invalid transaction body - Failed to validate vote schema: Array items are not unique (indexes 1 and 10) 
 not sure what to do, wont let me vote
