### ISSUE TITLE
Lisk Nano notified me of a negative balance

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-nano#477]
### Expected behaviour
Only notifies me of incoming transaction.

### Actual behaviour
When I forged a block, I received a notification stating ``You've just received -55.xxx LSK``. The notification included the 5 Forged LSK + the 50ish I was sending to someone else.

### Steps to reproduce
Forge a block and send transactions at the same time

**Comment by slaweet** [comment]
There's an attempt to fix this in `1.0.2` patch release. Not completely sure how the bug happened, so there's a chance it happens again. If so, please reopen.
