### ISSUE TITLE
timestamp error when voting

### ISSUE THREAD

**Issue by ramprat** [LiskHQ/lisk-nano#485]
Lisk nano 1.0.0 has the option to vote for delagates but when I vote for 33 or less I always get this error:

"Invalid transaction timestamp. Timestamp is in the future"

Win 10,
4 ram,
64 bit acer laptop

**Comment by slaweet** [comment]
Essentially this is the same bug as https://github.com/LiskHQ/lisk-nano/issues/365 
OS time on your computer is (at least) a few seconds in the future. 

This is the fourth report of this bug I know of. Though technically it's OS setup thing, we should do something about it. At least give a better error message.

**Comment by slaweet** [comment]
Closing as duplicate
