### ISSUE TITLE
Resolve Lisk address

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-nano#508]
The Lisk Nano wallet does not resolve the lisk address to the delegate name, like the Lisk web-wallet does :(

**Comment by slaweet** [comment]
@Joo5t thank you for the feedback, though I don't see what you mean. Can you describe where web wallet resolves the lisk address?

**Comment by Joo5t** [comment]
@slaweet I wasnt aware to post this issue here, so before that I posted it here: 
https://www.reddit.com/r/Lisk/comments/6p13ym/lisk_nano_wallet/ 
It seems MrV777 is aware of this issue and its on the roadmap to solve.
