### ISSUE TITLE
Add support for message encryption and decryption

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#536]
### Expected behaviour
Users should be able to encrypt messages with someone public key and decrypt messages with their private key. The overall style should be similar to sign/verify message.
### Actual behaviour
Not implemented

**Comment by slaweet** [comment]
Lisk-js supports this https://liskhq.github.io/lisk-js/example/experiment.html#encrypt

**Comment by pcdinh** [comment]
How large in size can the message be?

**Comment by pcdinh** [comment]
Is the message here stored in "data" field implemented in the pull request? https://github.com/LiskHQ/lisk/pull/470

**Comment by slaweet** [comment]
This message encryption feature in this issue is not meant to store the message onto blockchain. Therefore I believe that there is no size limit.

Support for "data" field https://github.com/LiskHQ/lisk/pull/470 will be implemented to Lisk Nano here: https://github.com/LiskHQ/lisk-nano/issues/595

It might be worth to integrate these two features together, but that would be another issue.

**Comment by pcdinh** [comment]
Thanks for clarification. So what does this ticket intend to solve?

**Comment by slaweet** [comment]
The goal of this issue is to implement the same form as lisk-js provides here:
https://liskhq.github.io/lisk-js/example/experiment.html#encrypt
https://liskhq.github.io/lisk-js/example/experiment.html#decrypt
Except for the "secret" field, because in Lisk Nano that already known from login.

The intended use case is that message is encrypted in Nano and sent by some other means (email, etc.).
