### ISSUE TITLE
Unify naming of components that use 'connect'

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#567]
### Expected behaviour
Often we have two components with a similar name - the real component and the component wrapped with `connect`. Those two should be named distinctly and consistently.
Research what other projects use and choose one way and use it consistently.
### Actual behaviour
Some examples different naming:
https://github.com/LiskHQ/lisk-nano/blob/development/src/components/header/headerElement.js
https://github.com/LiskHQ/lisk-nano/blob/development/src/components/toaster/toasterComponent.js
https://github.com/LiskHQ/lisk-nano/blob/development/src/components/passphrase/passphrase.js

**Comment by alepop** [comment]
@slaweet in my opinion, components organization should look like : 
```
.
└── components
    └── header
        ├── index.js
        ├── style.css
        └── ...
```
The `index.js` exports `component` and the connected version of component as a `deafult`.
