### ISSUE TITLE
my lisk coins disappeared

### ISSUE THREAD

**Issue by davidspears** [LiskHQ/lisk-nano#586]
### Expected behaviour
My lisk coins disappeared, my lisk address is 13722665518661557279L, I should have about 250 lisk coins in my account but instead there is 0. I logged out and logged back in the next day, they were gone.
### Actual behaviour
Dont know

**Comment by slaweet** [comment]
I tried to search for address `13722665518661557279L` in Lisk Explorer [0] and it doesn't find any record. That means it never had 250 LSK. 
I don't see what happened here. Maybe you were not using mainnet?

[0] https://explorer.lisk.io/

**Comment by davidspears** [comment]
This is crazy. Its like I was logged out of my lisk account and my password
was replaced. Can you use my ip to find anything?

**Comment by slaweet** [comment]
@davidspears do you know what address did your LSK come from? Can you share that? 
Or you can search for outgoing transactions of that address in Lisk Explorer [0]. 
Or if your LSK came from an exchange, can you check in your exchange history you sent them to `13722665518661557279L`? 
[0] https://explorer.lisk.io/

**Comment by davidspears** [comment]
I purchased through changelly, maybe you could find the transactions simply
using my ip address? Once I get to my laptop I should be able to give you
the exchange address

**Comment by davidspears** [comment]
14292512764254749593L
<https://explorer.lisk.io/address/14292512764254749593L>, this is the link
address that I had my coins sent to via chanelly.   had 3 transactions on
July 24th,  One on July 25th, and one on July 27th for a total of about 120
something lisk if not more. Please let me know what you need me to do next
to recover my lisk out that address to my new lisk address. Thank you.

**Comment by slaweet** [comment]
Closing this issue in an effort to clean this Github repo. If more help is needed, please open ticket in http://support.lisk.io
