### ISSUE TITLE
Fix eslint errors in test files

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-nano#588]
There are some eslint errors in these files :
- toaster.test.js
- passphraseGenerator.test.js
- transactionRow.test.js
- passphrase.test.js

**Comment by slaweet** [comment]
The problem is that Jenkins doesn't check this eslint on test files. There is an issue for that https://github.com/LiskHQ/lisk-nano/issues/548. Fixing that issues means fixing this one, too.
