### ISSUE TITLE
Nano Wallet: Sign in

### ISSUE THREAD

**Issue by 92civichatch1** [LiskHQ/lisk-nano#599]
I am trying to sign into my Nano wallet. I have the seed written out on paper. However, whenever I type it in the passphrase area...the "login" key never illuminates to select and actually sign in. 

Please help!
-JC

**Comment by slaweet** [comment]
There is a section in our FAQ:
https://docs.lisk.io/v1.1/docs/faq-security#section-i-am-typing-my-passphrase-into-lisk-nano-but-the-button-is-grayed-out-what-can-i-do-
I can also recommend this tool to check your passphrase validity. It gives some useful hints, like which word is not valid:
https://github.com/iancoleman/bip39

**Comment by Bitgor** [comment]
I am having a similar issue @slaweet and the provided link is a 404. Please advise on how to resolve this issue.

**Comment by slaweet** [comment]
@Bitgor I updated the link in my previous comment to work again.

**Comment by DamianZaczek** [comment]
What if none of the steps listed does not work and I can not log in anymore??

**Comment by slaweet** [comment]
@DamianZaczek you can try using our web UI https://login.lisk.io/ 
It is deprecated and will be removed in the future, but at the moment it is fully operational.

**Comment by jackngai** [comment]
I tried logging in with the web UI. It didn't work for me. I checked the bips word list and confirmed every word I wrote was on the list as written. I even tried copying and pasting each word from the list and it didn't work. I also tried Ian Coleman's passphrase validity checker and all I get is "invalid mnemonic". What else can I try?

**Comment by slaweet** [comment]
Closing this issue in an effort to clean this Github repo. If more help is needed, please open ticket in http://support.lisk.io
