### ISSUE TITLE
Passphrase unhide possibility

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#6]
It would be great to allow unhide passphrase while entering

**Comment by rferro** [comment]
It will be available in the next released version. Ty @karek314

**Comment by mmguide2003** [comment]
Why use a enforced passphrase when a chosen password is safer to store and remember. Passwords allow for storage of a series of secret memory triggers only. A passphrase requires it to be write in the original format, which is a major security flaw.

**Comment by karek314** [comment]
@mmguide2003  I think this is better approach #7 , but im not sure if they are open to add it, Typing wallet seed words each time is very painful i hope they will add local storage of passphrase with AES key encryption with traditional password or no password if user chose to.
