### ISSUE TITLE
Forging rank circle progress bar

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#600]
Shouldn't it be actually 100% filled for rank 1 ?
<img width="376" alt="screen shot 2017-08-13 at 12 03 02" src="https://user-images.githubusercontent.com/9548618/29284907-defa7524-812c-11e7-96b6-34e3019072b9.png">

**Comment by slaweet** [comment]
I can reproduce this on latest final release `1.0.2`. But the latest release candidate of `1.1.0` no longer has this issue, since the code has been rewritten.
