### ISSUE TITLE
Issues in forging tab

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#618]
### Expected behaviour
forging tab should work as before the migration
### Actual behaviour
forging tab
- shows Rank higher by 1 (compared to nano 1.0.0)
- doesn’t round LSK amounts to 2 decimal places
- Forged blocks don’t get updates after the initial load

**Comment by reyraa** [comment]
The previous version doesn't show Forged blocks header if the list is empty. instead it shows a message: _You have not forged any blocks yet._ I think it makes sense to keep the same behaviour.
