### ISSUE TITLE
Allow to sign in with 12,18,24 word passphrase

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#621]
Currently only 12 word seed is accepted. It should accept 12, 18 and 24.

**Comment by karek314** [comment]
My bad, it works already.

However, generating new account is still forced 12 words. I think there should be possibility to choose between 12,15,18,21,24. Hence i won't close this issue yet.

**Comment by slaweet** [comment]
Thank you for the suggestion, but 12 words is already a lot. We want to make Lisk for end-users as simple as possible. Adding multiple passphrase length options to "New account creation" goes against that.

**Comment by karek314** [comment]
I think there should be option - if you want to make it easier for most people, that's fine. But i bet some people would like to get 256 bits of security, instead 128. Why not lift up security if you can. 256 bits is more future proof and generally in case using as a bip39 seed, more secure due human readable format.
