### ISSUE TITLE
"Click to send all funds" out of balance rectangle.

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#638]
<img width="489" alt="screen shot 2017-08-23 at 01 46 48" src="https://user-images.githubusercontent.com/9548618/29592549-22983e0a-87a5-11e7-93e2-c0c4b2e10509.png">

It does happened with this balance length. Usually it's ok.

**Comment by mchl18** [comment]
at what resolution/window width? cannot seem to reproduce with same value

**Comment by karek314** [comment]
Default mode of latest release version of Lisk Nano. 
Macbook Pro 15,4-inch (2880 x 1800) However running on 
<img width="369" alt="screen shot 2017-08-27 at 20 06 57" src="https://user-images.githubusercontent.com/9548618/29752692-519f6a72-8b63-11e7-824b-db45c248178f.png">

**Comment by slaweet** [comment]
@karek314 does it still happen for you in yesterday released Lisk Nano 1.1.0? I could reproduce it with neither the previous nor the recent version.

**Comment by karek314** [comment]
Sorry for delay, i can't reproduce issue now. Marking as resolved.
