### ISSUE TITLE
Voting: It doesn't deselct properly but you notice it after you send out your Vote

### ISSUE THREAD

**Issue by Vaporleo** [LiskHQ/lisk-nano#653]
I votet for some Delegates with the Lisk Nano App before. Now I wanted to change my Voting and selected some Names. And deselected others. So there were 5 of wich I voted and 5 I unvoted. 

As I noticed I selected one of them wrong because of the similarity in names. Then I deselected the wrong one and selected the right one. And I did not Vote till now.

After that I saw at the Vote button: Vote (+5/-5). As it should be. I controled the names again and clicked Confirm.
After that the name I deselected was Voted for and the name I newly selected was not voted for but only selected and on the Vote button was: Vote (+1)

This was very upsetting because I had to pay for one more Vote to change the wrong vote to the right one.

**Comment by slaweet** [comment]
This should be solved in the yesterday released Lisk Nano 1.1.0
