### ISSUE TITLE
Unable to create new nano wallet on linux

### ISSUE THREAD

**Issue by mmquimby** [LiskHQ/lisk-nano#656]
### Expected behaviour
can create a new wallet, write down my 12 keywords, and transfer some lisk in

### Actual behaviour
twice wrote down the 12 keywords, verified one when asked, and then was sent back to the login screen. unable to create account.

got lots of these errors:
context mismatch in svga_sampler_view_destroy

### Steps to reproduce
download version lisk-nano-1.0.2-x86_64.AppImage to ubuntu 16.04
chmod a+x the file (shouldn't have to do this - file should come with this set)
run it
go through steps for new and end up back at login screen

**Comment by slaweet** [comment]
I tried to reproduce the steps with lisk-nano-1.0.2-x86_64.AppImage in Ubuntu 16.04 and I didn't get any errors. 
@mmquimby can you please provide some more information. The exact wording or screenshot of the errors would be useful.

**Comment by mmquimby** [comment]
There were no errors shown in the UI, it just took me back to the login screen. In the terminal window where I had started the wallet UI, I had lots of:

context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
...

**Comment by slaweet** [comment]
Thank you @mmquimby for the additional info. However, I still cannot reproduce the issue.

Does the same issue happen also with the latest version?
https://downloads.lisk.io/lisk-nano/1.1.0/lisk-nano-1.1.0-x86_64.AppImage

**Comment by mmquimby** [comment]
Yes, working in 1.1.0.
