### ISSUE TITLE
Transactions are in red

### ISSUE THREAD

**Issue by AlanBreazeale** [LiskHQ/lisk-nano#658]
I need help!!!  When I try to send from my Lisk Nano wallet, my last 3 transactions are in red with an arrow

**Comment by slaweet** [comment]
@AlanBreazeale "in red with an arrow" is as expected, that's how successful outgoing transactions are displayed. As opposed to incoming transactions that are in green and arrow in opposite direction. 

However, I see that it was not obvious and therefore our UI can be improved. Thank you for your feedback, we'll think of what to do about it. Right now I'm thinking of changing red to black and adding a tooltip to the arrow that says "Outgoing".
