### ISSUE TITLE
Where did my list coins go 

### ISSUE THREAD

**Issue by iowafishing** [LiskHQ/lisk-nano#659]
### Expected behavior 
I thought my list coins would show up in the nano wallet it shows zero coins. I had coins in my online wallet after ICO now it shows Zero?

**Comment by mchl18** [comment]
Can you please give your address or look it up on https://explorer.lisk.io/.
It will show all transactions done from the address, that way you can trace the coins

**Comment by iowafishing** [comment]
These Coins where in this Lisk online wallet after the ICO. I would like to
know where they went? My wallet shows no transactions so what happend? I
remember that there was confusion with the coins during the ICO. I thought
that was all figured out when I got my coins. Now nothing there??? I will
give my address but will it to everyone on the net from here?

**Comment by slaweet** [comment]
Closing this issue in an effort to clean this Github repo. If more help is needed, please open ticket in http://support.lisk.io
