### ISSUE TITLE
Voting - prevent allowing tagging same username twice and improve error message if not

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#660]
### Expected behaviour
I did not expect the voting UI like adding tags to allow the same person twice. And expected a better non-developer error message
### Actual behaviour
I was voting and the 1st username appeared twice some how. The error message mentioned 0 and 1 index and I don't think normal users would understand, even took me a while to figure it out. I then made some changes and the last user I voted for also appeared twice in the list somehow and I got the error message again.
### Steps to reproduce
Not sure, perhaps add vote from grid UI and also from the popup for the same person

**Comment by chauey** [comment]
![image](https://user-images.githubusercontent.com/5130533/29753072-fc52c3ee-8b93-11e7-8cce-0b95761915f9.png)
Here is image of the same person being listed twice somehow. also happened again with the last person i voted after i made some changes. I deleted the error message already :(

**Comment by chauey** [comment]
I'm actually also very confused about the blue, green, and red colors. The green seems to represent the ones being voted on but i had green ones with no votes on top right and popup. and i have many that are red which i have no unvoted. some test cases need to be done around this I believe. This could be a separate issue/ticket if desired but please try to reproduce. having a hard time check my votes to change them around some. 90% sure there is a bug around this. if i check the green and red ones, they reset and get added to the top right counters for + and - again. It was out of sync some how.

**Comment by chauey** [comment]
I continue to have problems with it and able to reproduce. tried to unvote and return vote, and unvote again, and shows up twice and went towards the count
![image](https://user-images.githubusercontent.com/5130533/29766945-c74e4fb6-8c0a-11e7-8d15-36c5ef010b17.png)

**Comment by chauey** [comment]
follow up to the colors comment 2 above. after i voted, there are still red and green which is very confusing. I would expect all the colors to be blue only for all checked/voted. Should be fresh, not showing any ready to be removed or added states.
![image](https://user-images.githubusercontent.com/5130533/29767113-6ac83ec2-8c0b-11e7-8170-08e2e93148bd.png)
GLHF!

**Comment by slaweet** [comment]
I can reproduce this on latest release 1.0.2. But the current development branch no longer has this issue, since the code has been rewritten. I will keep the issue open until the next version is released.

**Comment by slaweet** [comment]
This should be solved in the yesterday released Lisk Nano 1.1.0
