### ISSUE TITLE
Voting: allow pasting list of delegate usernames for faster voting enhancement

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#661]
### Expected behaviour
Would like to paste delimited list (space, comma, or semi-colon) of delegate usernames for faster voting. perhaps even 101 all at a time.
### Actual behaviour
Searching and voting for all 101 delegate is quite time consuming compared to what it could be, vastly improved user experience. :)
### Steps to reproduce
Vote for max 33 at a time, searching and checking for each delete 1 by 1.

**Comment by slaweet** [comment]
I think Launch Protocol https://github.com/LiskHQ/lisk-nano/issues/20#issuecomment-336443499 solves this use case. 

@chauey if you think otherwise, feel free to reopen.
