### ISSUE TITLE
ESLintError: "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style" Windows? 

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#663]
### Expected behaviour
Was hoping to download the source code and run the app.  
### Actual behaviour
Actually I can seem to get to "http://localhost:8080/#/", but the number of error messages in console is quite long.
### Steps to reproduce
run npm install and npm run dev (on Windows machine perhaps)

![image](https://user-images.githubusercontent.com/5130533/29769474-bd713ac6-8c14-11e7-842d-b28b483d0b17.png)

**Comment by slaweet** [comment]
@chauey I tried to fix this according to [eslint docs](https://eslint.org/docs/rules/linebreak-style) by this commit https://github.com/LiskHQ/lisk-nano/commit/daa47ef6ef9dc0eed530ef46da6bd5a107f6d1cb on branch [663-linebreak-style-eslint](https://github.com/LiskHQ/lisk-nano/commits/663-linebreak-style-eslint )
I tested it in a Windows 10 virtual machine, but I still got the errors when I run `npm run eslint`. Does the fix behave the same for you? If so, do you have any idea what's wrong?

**Comment by slaweet** [comment]
@chauey are you still interested in getting this fixed? If so, please respond to my previous comment. Else I'll close the issue since I know of no one else developing Lisk Nano on Windows.

**Comment by chauey** [comment]
@slaweet nothing urgent now for me on this, just wanted to try it out earlier and help report bugs. i suspect the git settings should handle this with pull or push but not sure what happened here. thx

**Comment by slaweet** [comment]
Thank you @chauey for the response. I'll leave the issue open, but won't work on it since the trivial fix doesn't work and nobody develops Nano on Windows, so there's currently no value in fixing it.
