### ISSUE TITLE
Custom node configuration is being forgotten

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#666]
### Expected behaviour
If users chose custom node, it should have save it's address and pre-set last used node configuration.
If user chose for example Testnet, then after logging out and signing with new account, it should be preset to Testnet instead always to Mainnet. Same apply to restarting app itself.

### Actual behaviour
It always resets itself to Mainnet and custom node configuration is forced to localhost.

**Comment by slaweet** [comment]
I can reproduce this on latest release 1.0.2. But the current development branch no longer has this issue, since the code has been rewritten. I will keep the issue open until the next version is released.

**Comment by karek314** [comment]
Okay, i will confirm if it's resolved.

**Comment by karek314** [comment]
It's resolved on 1.1.0 rc1.
