### ISSUE TITLE
Delegate search results can be duplicated on local dev

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#667]
### Expected behaviour
When searching for delegates, should never have duplicates in prod or dev
### Actual behaviour
In dev in chrome, am able to get duplicate results, like 2 rows with "thepool" in it. Could be a async problem? maybe using redux and not cancelling previous call when next debounce fires? haven't looked at the codes.
### Steps to reproduce
run locally on dev, type in "thepool" and delete the "l" and type it back at varying speeds to get some perhaps edge hard-to-reproduce case. was not able to reproduce yet in the released version. But would want to fix the dev version to be sure it doesn't happen in prod.

![image](https://user-images.githubusercontent.com/5130533/29772026-f195fb5a-8c20-11e7-9a6e-8e0eaeddf49a.png)

**Comment by slaweet** [comment]
Thank you @chauey for reporting this issue. 
What exact git revision did this happen on? 
I tried to reproduce it on `development` branch today, but I can see from the screenshot, that it is a bit older, as there are missing the css shadows that were fixed by this PR 4 days ago https://github.com/LiskHQ/lisk-nano/pull/648

**Comment by chauey** [comment]
I believe I had just forked the repo and was on development. Last commit was on 22nd in there?
![image](https://user-images.githubusercontent.com/5130533/29778910-242b3516-8c3b-11e7-880c-96210f25c87d.png)
5363467
uncommitted changes in pix is just package-lock.json file. 
I also noticed the odd style issues running in local dev local but not familiar enough if that was to be expected or not.

**Comment by chauey** [comment]
perhaps i have old version and need to rebase/refresh or something, i dno't see those css updates. sorry.

**Comment by chauey** [comment]
i rebased and got latest and can't reproduce. please feel free to close. sry, thx
