### ISSUE TITLE
Loading indicator is not dismissed

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#668]
### Expected behaviour
Loading indicator should always dismiss after completing action
### Actual behaviour
Loading indicator is not dismissed
### Steps to reproduce
Define non-existing custom node. example - localhost without node running locally.

**Comment by slaweet** [comment]
I can reproduce this on latest release `1.0.2`. But the current `development` branch no longer has this issue, since the code has been rewritten. I will keep the issue open until the next version is released.

**Comment by karek314** [comment]
Okay, i will confirm if it's resolved.

**Comment by karek314** [comment]
It's resolved on 1.1.0 rc1.

**Comment by karek314** [comment]
Actually, it some cases issue remains. But no in one described here - this one is fixed. Currently issue remains after using wallet / forging features.

**Comment by reyraa** [comment]
I've tried to break Api calls in forging tab, all working fine. Please provide me with a scenario to replicate the bug.

**Comment by karek314** [comment]
Seems it's resolved now.
