### ISSUE TITLE
Random delay in showing buttons after login

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#669]
### Expected behaviour
Entire interface should appear instantly

### Actual behaviour
Sometimes "send" and "logout" buttons do appear with significant delay.

### Steps to reproduce
Appears to be related to connectivity. Possible to reproduce with overloaded internet connection.

**Comment by slaweet** [comment]
I can reproduce this on latest release `1.0.2`. But the current `development` branch no longer has this issue, since the code has been rewritten. I will keep the issue open until the next version is released.

**Comment by karek314** [comment]
Okay, i will confirm if it's resolved.

**Comment by karek314** [comment]
It's resolved on 1.1.0 rc1.
