### ISSUE TITLE
Lisk Nano - search issue on MacOS version

### ISSUE THREAD

**Issue by fforrest** [LiskHQ/lisk-nano#670]
### Expected behaviour
On MacOS Nano wallet, searching for a keyword on "Vote for delegates" popup should display all possible delegate names for that particular keyword.

### Actual behaviour
On MacOS Nano wallet, searching for a keyword on "Vote for delegates" popup does NOT display all possible delegate names for that particular keyword.

### Steps to reproduce
1. Login to nano wallet on your MacOS
2. Go to Voting tab, click on Vote button at the top right of the tab and you get a "Vote for delegates" popup 
3. Search for 'bioly' and it displays only 2 delegate names - bioly_pool and bioly_donation
It should display 3 names - bioly, bioly_pool and bioly_donation

<img width="1035" alt="nanomacos" src="https://user-images.githubusercontent.com/25694555/29773211-f39c1e90-8c19-11e7-82cd-e52730cee6b4.png">

<img width="477" alt="nano_macos" src="https://user-images.githubusercontent.com/25694555/29773219-fac4bb64-8c19-11e7-9eb6-13e8956cb383.png">

**Comment by slaweet** [comment]
@fforrest thank you for reporting the issue.
The first idea that comes to my mind that that "Add vote to" is not listing delegate "bioly" because you already voted for that delegate and thus cannot vote for the same delegate again. Can that be the case?

**Comment by fforrest** [comment]
@slaweet I'm afraid no because this was faced/reported by a GDT voter who was voting for the first time and so had not voted for bioly till then. 
As a workaround we asked him to vote via the Search feature on the Voting tab itself instead of going to the pop-up window.

**Comment by fforrest** [comment]
Please note the "Vote for delegates" pop-up search feature works fine on Linux and Windows (10) version of Nano wallet, we checked.

**Comment by fforrest** [comment]
@slaweet I'll looked further into what you mentioned and it looks like you are right. 
Nano MacOS version does not show the names that you've already voted for. 

But the Linux and Windows version show the names even if one has voted them already, 
so it looks like the pop-up vote feature behaves differently in Mac version compared to Linux and Windows version. Hope this helps.

**Comment by slaweet** [comment]
@fforrest I'm running MacOS and Don't have a Window or Linux machine nearby at the moment. However, I'm highly confident that this feature is platform independent and works everywhere the same - does not show names already voted for. 
Anyway, I will check it on other platforms when I have a chance.

**Comment by fforrest** [comment]
@slaweet sure thanks, please check it. 
Around 2 members (cc001 and bioly) have checked it on Linux and it shows the names already voted for and 
2 other members (vi1son and mrv) checked it on Windows (7 & 10) and it also shows the names already voted for.

**Comment by slaweet** [comment]
@fforrest is this still a problem in the latest version of Lisk Nano?

**Comment by slaweet** [comment]
I believe that this issue no longer happens. Otherwise feel free to reopen.
