### ISSUE TITLE
missing lisk coins address

### ISSUE THREAD

**Issue by davidspears** [LiskHQ/lisk-nano#692]
### Expected behaviour
14292512764254749593L, this is the link address that I had my coins sent to via chanelly.   had 3 transactions on July 24th,  One on July 25th, and one on July 27th for a total of about 120 something lisk if not more. Please let me know what you need me to do next to recover my lisk out that address to my new lisk address. Thank you.
### Actual behaviour
Lisk password disappeared , replaced with new password some how, just found my actual lisk address that should have my balance showing
### Steps to reproduce'
Figure out how to get lisk from old address, to new address

**Comment by slaweet** [comment]
The only way to get the funds from an address is to create a send transaction signed by the passphrase that belongs to that address. 

When you create a new account in Lisk Nano it clearly states:
> This passphrase is not recoverable and if you lose it, you will lose access to your account forever. Please keep it safe!

If you don't know the passphrase, there is nothing we can do for you.

**Comment by davidspears** [comment]
At first you said if I knew my Lisk address you could recover my funds, I
know that NOTHING is lost forever , you will have better luck if you treat
people how you'd want to be treated especially if you have kids and that's
your last few hundred dollars you tried investing

**Comment by davidspears** [comment]
I will find the creator and the owner of lisk and show them these emails

**Comment by slaweet** [comment]
I certainly didn't say that you can recover your funds with your address because it is technically not possible. I know it's no good situation to be in, I've also lost a Bitcoin account some time ago. But with cryptocurrencies, there really is no way to recover only knowing the address.
