### ISSUE TITLE
(Auto-)Update function for Lisk Nano

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-nano#706]
### Expected behaviour
A menu entry to check for an update and download it (or better: auto-update).

### Actual behaviour
No update function.

**Comment by slaweet** [comment]
Thank you for the suggestion. I completely agree that we need this. There is already an issue for the feature scheduled for version`1.3.0` https://github.com/LiskHQ/lisk-nano/issues/196 so I'm closing this one as a duplicate.
