### ISSUE TITLE
Don't send secret to active peers

### ISSUE THREAD

**Issue by mfressdorf** [LiskHQ/lisk-nano#708]
### Expected behaviour
I expect to only send out signed transactions, so my passphrase never leaves my computer.

### Actual behaviour
Secrets are currently sent out for all transactions, this is a major security concern.

### Steps to reproduce
All transactional requests found in utils/api use "requestToActivePeer" (utils/api/peers.js), which uses the plaintext passphrase/secret in the "sendRequest" method of the lisk-js API utility.

This following transactions are affected:

* setSecondPassphrase - (utils/api/account.js)
* send - (utils/api/account.js)
* vote - (utils/api/delegate.js)
* registerDelegate - (utils/api/delegate.js)

**Comment by karek314** [comment]
I'm not from HQ, but 2 weeks ago i did ported entire lisk-js to php. All transactions are signed locally thus only signed transaction is broadcasted. Private key and passphrase are only used locally.

**Comment by Isabello** [comment]
Lisk-JS does not send out secrets. What you are see is lisk-nano passing secrets to the module internally, which resolve into promises that post full signed objects via the peers api layer.

**Comment by mfressdorf** [comment]
Ok, I was getting a bit too far ahead, this is an issue with the current development (and tagged for 1.0.0) version of Lisk-JS
Since Lisk-Nano is using Version 0.4.5, this issue is not relevant for now.
