### ISSUE TITLE
LSK disappeared

### ISSUE THREAD

**Issue by matthevandam** [LiskHQ/lisk-nano#709]
### Expected behaviour
On Sunday 03 September 2017 I downloaded the Lisk Nano wallet from https://lisk.io/download. I generated a passphrase which I printed out and stored in a password protected file. I transferred some LSK from Poloniex and a proper withdrawal ticket is recorded in the Poloniex history. The LSK duly showed up in the wallet after a little while. When I opened the wallet again a day later, the Balance showed 0 LSK. And that is what it still shows today - screen capture attached.

Any suggestions where the LSK went? What did I do wrong?
### Steps to reproduce
![lisk nano wallet](https://user-images.githubusercontent.com/31643563/30143387-bc66cee6-93af-11e7-8b79-8ab3ecbb5dbd.JPG)

**Comment by reyraa** [comment]
Check if the destination address shown in Poloniex is exactly this address. Check in the transaction Id Explorer to make sure your transaction is sent and confirmed. Please use one of our chat forums. this board is only for technical issues with Lisk Nano.
