### ISSUE TITLE
More user-friendly voting input validation error messages

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#718]
Minor enhancement.
### Expected behaviour
User-friendliness includes error messages and if user picks too many users to vote for, would expect an error message non-technical people would understand better. Instead of "... Array is too long...", perhaps something like "You can only vote for 33 delegates at a time. 34 were selected."
### Actual behaviour
![image](https://user-images.githubusercontent.com/5130533/30250444-975f872a-9678-11e7-8a6b-ce39d63deebe.png)

### Steps to reproduce
Choose over 33 delegates and try to vote for them

**Comment by slaweet** [comment]
Before the migration, we had check that disables the "Confirm" button if more than 33 delegates are selected.
There is an enhancement issue scheduled for the next version to give more aggregated info about selected delegates  https://github.com/LiskHQ/lisk-nano/issues/445 That should help.
