### ISSUE TITLE
Approval should never be more than 100%

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#719]
### Expected behaviour
Would not expect Approval to ever be more than 100%
### Actual behaviour
I see on test net, approval for cc001 is at 100.49%. My guess is some math is incorrect. I am not familiar with that this is or how it's calculated.
![image](https://user-images.githubusercontent.com/5130533/30250490-70701c28-9679-11e7-8bf8-bcede3ab6c6b.png)

### Steps to reproduce
Log in to testnet and noticed the 1st person to vote for cc001 has over 100% Approval

**Comment by slaweet** [comment]
I forwarded the issue to Lisk Core: https://github.com/LiskHQ/lisk/issues/782 since Nano is only displaying the data it gets from the node.
