### ISSUE TITLE
MY VOTES modal dialog, the X does not seem to delete/remove anything

### ISSUE THREAD

**Issue by chauey** [LiskHQ/lisk-nano#722]
### Expected behaviour
In the MY VOTES model dialog, there is a huge "X" to the right of each row for the list of delegates voted for. The big "X" is most likely to delete/remove.
### Actual behaviour
Click on the "X" seems to do absolutely nothing.
### Steps to reproduce
Click MY VOTES to open the dialog, click on the "X" for any item.

![image](https://user-images.githubusercontent.com/5130533/30252555-deff1bd8-969e-11e7-86f3-aec93aceb1bf.png)

![image](https://user-images.githubusercontent.com/5130533/30252552-d71e4e5c-969e-11e7-8004-5b5b5a1021f5.png)

**Comment by slaweet** [comment]
Good point. IMO the solution should be to mark the removed delegate (in red?) and change the x icon to some "Redo" icon like this:
![re-icon](https://user-images.githubusercontent.com/1254342/30262065-a95eeb62-96cf-11e7-9cb6-ff491b5ffba7.png)
