### ISSUE TITLE
LISK sent from Wallet to Bittrex address not showing up

### ISSUE THREAD

**Issue by bigcatstins** [LiskHQ/lisk-nano#729]
### Expected behaviour
-expected transaction to be received by Bittrex within 30 min
### Actual behaviour
-transaction taking over 9 hours now
### Steps to reproduce
-not sure
<img width="602" alt="capture12" src="https://user-images.githubusercontent.com/17462055/30286092-a39e23d8-96dd-11e7-8be9-61f4a3484042.PNG">

**Comment by slaweet** [comment]
If you mean the transaction you've sent to `944889642186726236L`, it is correctly processed on Lisk blockchain [0], therefore it's a matter of Bitterex and I suggest contacting Bitterex support.
[0] https://explorer.lisk.io/address/944889642186726236L
