### ISSUE TITLE
Optimise updates based on confirmed transactions

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-nano#746]
### Expected behaviour
We can create a function which iterates over transactions once, and accepts multiple filter functions in pipeline and returns the result once. this saves us from ending up to multiple redundant iterations over all the transactions with every beat of metronome.

### Actual behaviour
Presently we filter transactions 3 times for 3 similar goals:
 - To get the list recent of transactions with _vote_ type.
 - To get the list recent of transactions with _register as delegate_ type.
 - To update the number of confirmations

### Where all these happen
in `store/middlewares/account.js`

**Comment by slaweet** [comment]
It turned out that it would add unnecessary complexity to the code, so we won't do this.
