### ISSUE TITLE
Improve saveAccount utility code

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-nano#774]
There are some issues with the [saveAccount](https://github.com/LiskHQ/lisk-nano/blob/development/src/utils/saveAccount.js) utility worth fixing:
 - We're creating an array, but actually never adding a new member to it.
 - We call remove account but we remove entire array. which brings up, why an array then?
 - none of the methods return a response to the caller.
 - None of the methods are covered with unit tests.

**Comment by slaweet** [comment]
This was fixed with https://github.com/LiskHQ/lisk-nano/pull/966
