### ISSUE TITLE
Floating-point arithmetic rounding error in balance

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#80]
balance returned form the API is: `"balance":"9999997590000000"`
but the ui shows: 99999975.90000001 LSK
![round_issue](https://cloud.githubusercontent.com/assets/1254342/24456643/f80a95ae-1493-11e7-99d8-8063dc403b15.png)

**Comment by slaweet** [comment]
I think it happens only for an account with very high balance, thus it won't happen to any user on main net. I tried to reproduce it with lower balance, but it didn't happen.

**Comment by karmacoma** [comment]
Closed by #90
