### ISSUE TITLE
Multiple white spaces between passphrase words lead to different account

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-nano#835]
### Expected behaviour
Additional white spaces between words in the passphrase should be recognized and dismissed as non-valid like login.lisk.io does correctly

### Actual behaviour
Lisk Nano accepts this wrong passphrase and leads to a different account

### Steps to reproduce
generate an account.
add additional white space(s) between the words.
Nano does not complain, enters a different account. login.lisk.io does it correctly (preventing the login).

**Comment by alepop** [comment]
PR about it #815

**Comment by simonmorgenthaler** [comment]
oh, thx :)
