### ISSUE TITLE
Remove submitting on enter in vote form

### ISSUE THREAD

**Issue by ginacontrino** [LiskHQ/lisk-nano#840]
### Expected behaviour
When we want to add or remove a vote for a delegate, it should not be possible that the form submits on enter. Only the specific click action on "confirm" should submit the form. 

### Actual behaviour
Currently, when selecting a delegate and pressing enter, the entire form submits. 

### Steps to reproduce
- Go to "vote"
- Search for a delegate in "Add vote to" or "Remove vote from" and select a delegate
- press enter -> the selected delegate is added and the form submits in the same step

**Comment by alepop** [comment]
My bad. Did not check it for this case.

**Comment by slaweet** [comment]
I think it's my bad, @alepop. I specifically asked for this in vote dialog in https://github.com/LiskHQ/lisk-nano/issues/755 without thinking too much about the consequences.
