### ISSUE TITLE
Select network in login dialog

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#89]
It doesn't really make sense change network after login, as user most likely doesn't have the same account address on all mainnet, testnet, localhost.
Just add a simple dropdown with 3 options:
 - Official, 
 - Testnet, 
 - Localhost

The first should be the default.

Then the peer card in the UI after login should only list nodes on the selected network.

**Comment by karek314** [comment]
It would be great to define fully custom node, possibility to define ip/domain and add to this dropdown menu.
