### ISSUE TITLE
Add .npmrc file

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#894]
### Expected behaviour
Add .npmrc file with `save-exact`
https://docs.npmjs.com/misc/config#save-exact
Like lisk-js team  did https://github.com/LiskHQ/lisk-js/issues/380

**Comment by willclarktech** [comment]
FYI: yarn does not currently support this.

**Comment by mpuk** [comment]
@slaweet  Hi. Can I do this?

**Comment by slaweet** [comment]
Yes, @mpuk, you're welcome to work on this. If you'll have any questions, feel free to ask here or on [Lisk Gitter](https://gitter.im/LiskHQ/lisk)

**Comment by mpuk** [comment]
@slaweet I just wanted to ask in which branch this should be done.

**Comment by slaweet** [comment]
Good question @mpuk. You can use `1.3.0` as a base. Then we use issue number in the feature branch name, e.g. `894-add-npmrc-file.
We should address this kind of questions in our contribution guidelines, but so far we didn't get to it.

**Comment by mpuk** [comment]
@slaweet Understood. I will submit PR today. And if you want you can make issue about updating contributing guide.
