### ISSUE TITLE
Possibility to vote

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#9]
Lisk Nano may also contain simple interface to vote on delegates, with easy search engine. User provide delegate name, and if found can vote from Lisk Nano.

**Comment by karmacoma** [comment]
@karek314: Lisk nano is purely intended for sending simple transactions, i.e. not other types of transactions. We are planning on a full rewrite of the existing Lisk Full client, and indeed a Lite Client will be an option.
