### ISSUE TITLE
Delegate voting issue

### ISSUE THREAD

**Issue by henk1234567890** [LiskHQ/lisk-nano#901]
### Expected behaviour

Being able to vote/unvote up to 33 delegates per voting turn. 

### Actual behaviour

When having 101 active votes, I cannot unvote/vote with 1 voting turn. Appears to be a bug, not deducting the unvotes from the total number of active votes in the voting process. The confirm button remains greyed out. I had to use 2 voting turns to change 4 votes.

### Steps to reproduce

When having 101 active votes, try to unvote one and vote another delegate in one voting turn.

**Comment by slaweet** [comment]
Duplicate to https://github.com/LiskHQ/lisk-nano/issues/932
