### ISSUE TITLE
Launch protocol doesn't work on Linux

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#909]
### Expected behaviour
lisk://main/transactions/send?recipient=537318935439898807L&amount=100
Should open Lisk Nano on Linux the same way it works on Windows and Mac.
### Actual behaviour
Reported by @simonmorgenthaler:
those lisk:// links don't work in my linux. it doesn't know that it should open it with Lisk nano

I installed the .deb amd64 version. I managed to get the lisk: link open nano from chrome by making the correct mime/.desktop configuration. but it does not open the specific functionality in nano, only the main page

**Comment by alepop** [comment]
@slaweet https://github.com/electron/electron/issues/6440

**Comment by punkrock** [comment]
Same problem on Windows 10 Enterprise, 64-Bit. Tested with latest Chrome and latest Firefox. Lisk Nano doesn't open, when visiting `lisk://main/transactions/send?recipient=537318935439898807L&amount=100`. Both browsers just try google for it.
