### ISSUE TITLE
Signed build for macOS and Windows

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-nano#91]
Binary for macOS should be signed with valid developer program, except signing - it to allow hassle free usage it might be also distributed through Mac App Store optionally.

```
codesign -dv "Lisk Nano.app"    
Lisk Nano.app: code object is not signed at all
```

**Comment by Isabello** [comment]
We have some options, we can buy a Cert from digicert: https://www.digicert.com/code-signing/apple-certificates.htm
Or we can use self signed. https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html

**Comment by karek314** [comment]
It's overpriced, this digicert claims ~178 usd per year.
Self-signed will force user to alter settings in Mac OS to allow software by non-apple developers which not everyone do.

Simplest solution is to enrol in Apple Developer Program as LightCurve or as Lisk Foundation. Then join program for 99$ per year. With such way build can be signed for Mac App Store and other distribution. Then user can keep tightest security settings and open app with one click like any other.

**Comment by karek314** [comment]
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

Codesign can be used for non xcode projects.

**Comment by Isabello** [comment]
I dont have any issues running the .dmg as it is now...

**Comment by karek314** [comment]
Dmg is not a problem, .app is.

<img width="342" alt="screen shot 2017-04-13 at 19 41 55" src="https://cloud.githubusercontent.com/assets/9548618/25016695/540fb098-2081-11e7-8676-e64bedf6c4a8.png">

Currently before running app first time i have must ctrl+click > open to start it. Since it's unsigned.

**Comment by karek314** [comment]
This is exactly what i mean
<img width="403" alt="screen shot 2017-04-18 at 21 14 34" src="https://cloud.githubusercontent.com/assets/9548618/25148719/216279f6-247c-11e7-9c2e-54b476451199.png">

**Comment by karmacoma** [comment]
@karek314: We hear you. It will be done.

**Comment by karmacoma** [comment]
This is now done. `0.2.1` will be released with signed packages for Windows and Mac.
