### ISSUE TITLE
Account creation: 13th word issue

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-nano#917]
### Expected behaviour
Lisk Nano should never asked for a 13th word, because it only creates 12-words-passphrases.

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/1260700/31994148-f01e2d1a-b97f-11e7-980e-8dc7bae11604.png)

### Steps to reproduce
Create accounts until you get asked for the 13th word

**Comment by reyraa** [comment]
@punkrock  Which version you are using?

**Comment by punkrock** [comment]
It was on 1.1.0, sorry. I didn't test on the latest 1.2.0. Doing now. or did you already fix it in latest 1.2.0?

**Comment by reyraa** [comment]
@punkrock yes it is fixed.
