### ISSUE TITLE
Make react app compatible for all browsers

### ISSUE THREAD

**Issue by ginacontrino** [LiskHQ/lisk-nano#968]
### Expected behaviour
The react app should work in the following browsers:
<img width="919" alt="screen shot 2017-11-07 at 11 48 21" src="https://user-images.githubusercontent.com/9592216/32489901-aa0a9c3c-c3b1-11e7-8903-2116d4756738.png">

### Actual behaviour
There will be some issues (probably especially in IE), so we should collect bugs and style issues here

### Steps to reproduce
I changed my mind :D

**Comment by alepop** [comment]
Is this really necessary? Because Lisk Nano shipped as Electron app and you need to cover all bugs only for Chrome

**Comment by ginacontrino** [comment]
After considering this a bit more, I changed my mind :D
