### ISSUE TITLE
Save account and than forget account results in account still logged to lisk-nano

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk-nano#987]
### Expected behaviour
When forgetting account, expect result will be that the user will be logged out. 
### Actual behaviour
a message is send (forgetting account), but the account stays logged to lisk-nano
### Steps to reproduce
log to lisk-nano
choose save account
choose forget account

**Comment by slaweet** [comment]
With the changes in Nano 1.3.0, the situation is different and now it IMO makes sense to stay logged in.
