### ISSUE TITLE
issues with transfers

### ISSUE THREAD

**Issue by Maras23** [LiskHQ/lisk-nano#989]
when sending I am getting this error message

Error

Invalid transaction timestamp. Timestamp is in the future

**Comment by biolypl** [comment]
Hello @Maras23 , I recommend you to update your Lisk Nano to newest release and try to sync your local clock.

**Comment by Maras23** [comment]
thank you for support, I had old version of the wallet. However it did not fix the problem; how to sync local time with wallet?

**Comment by mrv777** [comment]
The clock on your computer is off by too much. You just need to correct it to the sacond

**Comment by punkrock** [comment]
If you are using Windows, I reccomend to install this: http://www.timesynctool.com/
Install it as a service and let it run in the background. It will keep your system time always in sync.

**Comment by Maras23** [comment]
perfect guys, thanks a lot
